version: '3'
services:
  mysql:
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
  minio:
    image: minio/minio:RELEASE.2020-11-13T20-10-18Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
  elacticmq:
    image: softwaremill/elasticmq:0.15.8
    volumes: 
      - ./elasticmq.conf://opt/elasticmq.conf:ro
